### PR TITLE
Opening New Pull Request

### PR DESCRIPTION
**Pull request by mexiquin**
Made minimal changes from the last pull request, just some white spaces, for the purpose of creating a new open pull request for the code review portion of the project.

Notable changes from the last pull request (that I accidentally merged):

- Created F1 method that contains/encapsulates operations that use mantissa & characteristic methods
- Eased up on using the main() method. Its new job is simply for debugging & sample output.

### CODE REVIEW

**Comment by igorsteinmacher** [comment]
Thanks for that
Group 3 will review it

**Comment by YHL555** [comment]
The overall code looks good, with enough comments and easy to tell where some functions, loops, or if/else blocks begin and end. But, does not handle illegal characters, for example: "12,3-4",

**Comment by las589** [comment]
Thank you for the response, however, I believe the instructions for F1 state that the program does not have to handle dashes or any weird characters. It should return false. This program does this as well as print out that the input is not valid.

**Comment by YHL555** [comment]
Sorry, I am wrong, you are right.
Good Job !

**Comment by zhicenliu** [comment]
You did a good job. I like your comments, which makes your code look clear and simple.

**Pull request closed without merging**
